# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "Nicolas Quiceno"

# URL
baseurl:            ""
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title.html

twitter_username: nquicenob
github_username:  nquicenob

# Markdown
markdown:           rdiscount

# Navigation
nav:
  - name:           "About"
    href:           "about"
  #- name:           "Download"
  #  href:           "//github.com/gfjaru/Kiko/releases"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
